package bot

// action IDs
const (
	DontRemindMe             = "dont_remind_me"
	Email                    = "email"
	FirstMessageACK          = "first_message_ack"
	FirstMessageACKAt        = "first_message_ack_at"
	FirstMessageACKAtPicker  = "first_message_ack_at_picker"
	FirstMessageACKOption    = "first_message_ack_option"
	FirstMessageSentAt       = "first_message_sent_at"
	FirstMessageSentAtPicker = "first_message_sent_at_picker"
	FirstMessageSentOption   = "first_message_sent_option"
	FirstSent                = "first_message_sent"
	Reload                   = "reload_settings_modal"
	RemindMe                 = "remind_me"
	SerialInput              = "serial_input"
	SerialNumber             = "serial_number"
	Start                    = "start_settings_modal"
	TruthyNo                 = "false"
	TruthyYes                = "true"
	TZOffset                 = "tz_offset"
	Yes                      = "Yes"
	No                       = "No"
)

// callback IDs
const (
	AckIT                = "ack_it"
	AdminExclusionModal  = "admin_exclusion_modal"
	ExclusionModal       = "exclusion_modal"
	ExclusionQuestion    = "exclusion_question"
	ExclusionAddQuestion = "exclusion_add_question"
	ExclusionApprover    = "exclusion_approver"
	RemindMeQuestion     = "remind_me_question"
	ReminderPicker       = "reminder_picker"
	StopCuebertApproval  = "stop_cuebert_approve"
	StopCuebertRequest   = "stop_cuebert_request"
	UpdateUserQuestion   = "update_user_question"
	UpdateUserSelector   = "user_update_selector"
	UpdateUserSubmit     = "update_user_submit"
	UserReminder         = "user_reminder"
	UpdateUser           = "update_user"
	UsersSelect          = "users_select"
	YesExclusion         = "yes_exclusion"
	NoExclusion          = "no_exclusion"
	YesAddExclusion      = "yes_add_exclusion"
)

// modal and attachment fields
const (
	Accept                = "accept"
	ApproveExclusion      = "approve_exclusion"
	ApproveStop           = "approve_stop"
	BypassOverrideNo      = "bypass_override_no"
	BypassOverrideYes     = "bypass_override_yes"
	DatePicker            = "datePicker"
	DeviceBox             = "device_box"
	DenyExclusion         = "deny_exclusion"
	DenyStop              = "deny_stop"
	DocsBtn               = "docs_btn"
	ExclusionAddYes       = "exclusion_add_yes"
	ExclusionDatePicker   = "exclusion_date_picker"
	ExclusionInput        = "exclusion_input"
	ExclusionNo           = "exclusion_no"
	ExclusionReason       = "exclusion_reason"
	ExclusionReasonHeader = "exclusion_reason_header"
	GroupDM               = "group_dm"
	HelpBtn               = "help_btn"
	ReminderPickerHeader  = "reminder_picker_header"
	StopCuebertDeny       = "stop_cuebert_deny"
	StopCuebertNo         = "stop_cuebert_no"
	StopCuebertOverride   = "stop_cuebert_override"
	StopCuebertYes        = "stop_cuebert_yes"
	TimePicker            = "time_picker"
	UpdateConfigYes       = "yes_update_config"
	UpdateConfigNo        = "no_update_config"
	UserUpdateModal       = "user_update_modal"
	UpdateUserNo          = "no_update_user"
	UserUpdateSubmit      = "user_update_submit"
	UpdateUserYes         = "yes_update_user"
	UserDevices           = "user_devices"
	VersionBtn            = "version_btn"
)
