---
name: gen-puml-diagram
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    name: docs
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x

    - name: checkout the repo
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

    - name: install goplantuml
      run: |
        go get github.com/jfeliu007/goplantuml/parser
        go install github.com/jfeliu007/goplantuml/cmd/goplantuml@latest

    - name: install dependencies
      run: |
        sudo apt-get install graphviz -y

    - name: download plantuml
      run: |
        HASH="0a200db6e485c18206fc98e3ba1b44876c31bcec167ec0d5f152eb67c87aad46"
        curl -LO https://github.com/plantuml/plantuml/releases/download/v1.2023.8/plantuml-1.2023.8.jar
        DOWNLOAD_HASH=$(shasum -a 256 plantuml-1.2023.8.jar | cut -f 1 -d' ')
        if [[ "$DOWNLOAD_HASH" == "$HASH" ]]; then
            echo "downloaded hash: $DOWNLOAD_HASH matches."
        else
            echo "downloaded hash: $DOWNLOAD_HASH does not match expected - $HASH. please check for update"
            exit 12
        fi

    - name: generate puml
      run: |
        goplantuml -show-connection-labels -show-aggregations -recursive -title="Cuebert Diagram" . > cuebert.puml
        java -DPLANTUML_LIMIT_SIZE=14336 -jar "${{ github.workspace }}/plantuml-1.2023.8.jar" -tpng cuebert.puml 
        mkdir -p "${{ github.workspace }}/.docs/diagram/"
        mv -v cuebert.png "${{ github.workspace }}/.docs/diagram/"
        rm cuebert.puml

    - uses: gr2m/create-or-update-pull-request-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      with:
          author: "Cue Bot <cue@local.com>"
          path: ".docs/diagram/"
          commit-message: "updating diagram"
