---
name: readme-images

on:
  workflow_dispatch:

jobs:
  build:
    name: images
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x

    - name: checkout the repo
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

    - name: get termshot
      uses: robinraju/release-downloader@v1.7
      with:
        latest: true
        repository: homeport/termshot
        fileName: termshot_0.2.5_linux_amd64.tar.gz

    - name: install termshot
      run: |
        tar -xvf termshot_0.2.5_linux_amd64.tar.gz
        mv termshot /usr/local/bin

    - run: |
        make tidy
        make cue
        bash resources/scripts/readme-images.sh

    - uses: gr2m/create-or-update-pull-request-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      with:
          author: "Cue Bot <cue@local.com>"
          path: "resources/images/"
          commit-message: "updating images"
